version: '3.9'
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: bermuda_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bermuda
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bermuda_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: bermuda_qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  pg_data:
  redis_data:
  qdrant_storage:

