version: '3.9'
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: bermuda_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bermuda
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    image: bermuda-buddy-api:latest
    environment:
      POSTGRES_URL: postgresql+psycopg://postgres:postgres@postgres:5432/bermuda
      NWS_USER_AGENT: ${NWS_USER_AGENT}
      APP_VERSION: ${APP_VERSION:-0.1.0}
      MIGRATE_ON_START: '1'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8000:8000'

  web:
    build:
      context: ../
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: http://localhost:8000
    image: bermuda-buddy-web:latest
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    depends_on:
      - api

volumes:
  pg_data:

